### ISSUE TITLE
wlroots 0.18 support

### ISSUE THREAD

**Issue by diederikdehaas** [phkaeser/wlmaker#107]
wlroots 0.18 has been released: https://gitlab.freedesktop.org/wlroots/wlroots/-/releases/0.18.0

And in Debian there's [a transition tracker](https://release.debian.org/transitions/html/auto-wlroots.html) for it, so it would be great if wlmaker would support wlroots 0.18 too.

**Comment by phkaeser** [comment]
Actually there's already a branch at https://github.com/phkaeser/wlmaker/tree/nvidia that is updated to run with wlroots-0.18. It will need to get that cleaned up a little, and compile conditionally to support both 0.17 and 0.18 for smooth transition.

**Comment by diederikdehaas** [comment]
Ok, great! I did look in issues and PRs, but not in other branches.

**Comment by phkaeser** [comment]
With #114, the code is supposed to be ready for 0.18, and github actions in place to keep it building for both 0.17 and 0.18. For Debian Trixie, it's also verified to work with pre-packaged `libwlroots-dev` and has many fewer depdencies. That should also apply to BSD.

@alexmyczko -> is there something I can help with adjusting the Debian package? And, anything further needed to let it build against wlroots-0.18 ?

@jbeich -> similar for *BSD, it should build with system wlroots. Anything I can help updating?

**Comment by alexmyczko** [comment]
@phkaeser I guess all is fine, release a new version. You can see here:

https://sources.debian.org/src/wlmaker/0.3-2/debian/

in the changelog what is done in the latest package, and in patches/ you will find things that get patched for the package.

Debian 13 (trixie) will not be released before next year, and the freeze is also likely not to start before end of this year. https://release.debian.org/trixie/freeze_policy.html

Freezes usually take ~6 months, +-3 months.

**Comment by jbeich** [comment]
Builds fine on FreeBSD with both wlroots 0.17 and 0.18. Runtime is broken (unlike labwc-0.8, dwl-0.7, sway-1.10) with wlroots 0.18 but only on some FreeBSD versions. I'll file a bug later after narrowing it down more.

**Comment by jbeich** [comment]
I've opened #117 for the FreeBSD bug. It's easy to work around downstream, so not a blocker for (0.4) release.

**Comment by alexmyczko** [comment]
wlmaker 0.4.1 looks good and was just uploaded to debian, see https://buildd.debian.org/status/package.php?p=wlmaker&suite=sid soon

**Comment by phkaeser** [comment]
Glad we finally got it to work for Sid! -- and saw it uses 0.18 there :)

@alexmyzcko -- will 0.4.1 also make it into Trixie?

**Comment by alexmyczko** [comment]
in 4 days: https://qa.debian.org/excuses.php?package=wlmaker

**Comment by phkaeser** [comment]
@alexmyczko now shows as "blocked". Is that due to the wlroots dependency that has it's upgrade challenge?

(wlmaker should build against 0.17 and 0.18. Does debian have an explicit wlroots 0.18 package it should be configured against?)

**Comment by diederikdehaas** [comment]
It's build against [libwlroots-0.18-dev](https://packages.debian.org/sid/libwlroots-0.18-dev) which resulted in a runtime dependency against [libwlroots-0.18](https://packages.debian.org/sid/libwlroots-0.18), so for ``wlmaker`` everything is as it should be (thanks!).  
The [(migration) problem](https://tracker.debian.org/pkg/wlroots) is 2 fold:
- wayfire which is [working on wlroots 0.18 compatibility](https://github.com/WayfireWM/wayfire/pull/2452)
- phoc is [aware](https://gitlab.gnome.org/World/Phosh/phoc/-/issues/377) and [working on it](https://gitlab.gnome.org/World/Phosh/phoc/-/merge_requests/528), but I'm a bit confused as the RC Debian bug about it which blocks migration is [reassigned to wlroots source package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1085192), so maybe there will be wlroots-0.17 packages as well?

**Comment by phkaeser** [comment]
Thanks for explaining, @diederikdehaas !

**Comment by diederikdehaas** [comment]
Thanks for adapting it to wlroots 0.18 :+1: 

And with that conclusion, I can conclude that this issue is fixed. Thanks :)

**Comment by phkaeser** [comment]
Yay! 0.4.1 finally made it into Debian 13!

https://tracker.debian.org/news/1599527/wlmaker-041-2-migrated-to-testing/
