### ISSUE TITLE
Unused dependencies with system wlroots

### ISSUE THREAD

**Issue by jbeich** [phkaeser/wlmaker#12]
If there's no plan to use those in immediate future maybe remove.
```diff
 $ export LDFLAGS=-Wl,--as-needed
 $ cmake -B /tmp/wlmaker_build
 [...]
 -- Checking for module 'wlroots>=0.17'
 --   Found wlroots, version 0.17.1
 [...]
 $ cmake --build /tmp/wlmaker_build
 $ readelf -d /tmp/wlmaker_build/src/wlmaker | fgrep NEEDED
@@ -1,10 +1,7 @@
- 0x0000000000000001 NEEDED               Shared library: [libncursesw.so.9]
  0x0000000000000001 NEEDED               Shared library: [libtinfow.so.9]
  0x0000000000000001 NEEDED               Shared library: [libcairo.so.2]
- 0x0000000000000001 NEEDED               Shared library: [libdrm.so.2]
  0x0000000000000001 NEEDED               Shared library: [libwayland-client.so.0]
  0x0000000000000001 NEEDED               Shared library: [libwayland-server.so.0]
  0x0000000000000001 NEEDED               Shared library: [libwlroots.so.12]
- 0x0000000000000001 NEEDED               Shared library: [libpixman-1.so.0]
  0x0000000000000001 NEEDED               Shared library: [libxkbcommon.so.0]
  0x0000000000000001 NEEDED               Shared library: [libc.so.7]
```

**Comment by phkaeser** [comment]
Thanks for reporting! 

* libdrm and libpixman come from wlmaker:
https://github.com/phkaeser/wlmaker/blob/ed7a302fa78717ac496aeb2f2bd3256618f07d99/src/CMakeLists.txt#L131

libncursesw (most likely) from libbase:
https://github.com/phkaeser/libbase/blob/c215f7dbedc624ff29808882c2e0015d4a584b77/CMakeLists.txt#L110

**Comment by phkaeser** [comment]
A

**Comment by phkaeser** [comment]
Coming to terms with githubs workflos...

@jbeich => it appears Linux readelf doesn't show the unused dependencies, so I cannot easily verify if that addresses it. Might take a while until I get to compile it on a FreeBSD image.

If you find time to verify: Please update whether this resolves the curses dependency.
(if not: I'll eventually get to it...)

**Comment by jbeich** [comment]
> it appears Linux readelf doesn't show the unused dependencies

That was just a regular diff on `readelf -d` output from a build with vs. without `-Wl,--as-needed`. I confirm, there's no difference anymore.

See also [downstream build log](https://github.com/phkaeser/wlmaker/files/13968872/wlmaker-0.1.433.log) after [removing `-Wl,--as-needed`](https://github.com/freebsd/freebsd-ports/commit/db477b08af94).

**Comment by jbeich** [comment]
More accurately, on FreeBSD < 14 `ncursesw` is actually used as there's no [`tinfow`](https://github.com/freebsd/freebsd-src/commit/396851c20aeb) but on FreeBSD >= 14 `-Wl,--as-needed` removes `ncursesw`. libbase is a `STATIC` library, so either `ncursesw` or `tinfow` has to be linked.
