### ISSUE TITLE
smithay instead of wlroots?

### ISSUE THREAD

**Issue by soloturn** [phkaeser/wlmaker#121]
(sorry for creating an issue, it would be a discussion entry more appropriately)

helping to package [COSMIC desktop envirnoment](https://en.wikipedia.org/wiki/COSMIC_(desktop_environment)) for arch linux, i stumbled via its wayland library [smithay](https://github.com/Smithay/smithay), [remote desktop via wprs, i.e. "tmux for windows"](https://github.com/wayland-transpositor/wprs) (remote GUI is actually my personal problem space), [its older inspiration, xpra](https://en.wikipedia.org/wiki/Xpra), a blog post [questioning if wayland breaks everything](https://pointieststick.com/2023/12/26/does-wayland-really-break-everything/), probonopds [wayland x11 compatibility protocols](https://github.com/probonopd/wayland-x11-compat-protocols/) to your [presentation][https://www.youtube.com/watch?v=yNSdIvdJeSw] and implementation of [ext_toplevel_icon_v1 to set window icons](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/269), and your presentation  . it really [got implemented in smithay](https://github.com/Smithay/smithay/issues/781).  very cool :) 

but as you are in tradition of revolutionaries tim berners lee, and nextstep, i was wondering why you base your work on dusty wlroots, and not on rusty smithay?

an unrelated remartk ... for IAM ... there is rusty [kanidm](https://github.com/kanidm/kanidm).

**Comment by phkaeser** [comment]
Thanks for sharing the pointers and the suggestion! Smithay looks interesting & promising, and if I were to (re)start all over and in Rust, that would be a a likely dependency.

How come I have not been using it already? In short:
* I had started wlmaker in mid 2022; and it appears Smithay hadn't been released yet back then.
* For various reasons, I opted to write wlmaker in C; and smithay in Rust would add extra challenges.

It's great to see there's a strong & growing library base for Rust. 
I'd love to make use of it; if just time permitted me more hacking time :)
