### ISSUE TITLE
Can't build 0.4?

### ISSUE THREAD

**Issue by alexmyczko** [phkaeser/wlmaker#133]
I saw the latest release, and I've tried to build it, but no luck for me: http://bananas.debian.net/debian/wlmaker/6/

What am I doing wrong?

wlmaker without startx works great btw, it's just no fun on high res display (too small).

**Comment by phkaeser** [comment]
Have looked only briefly, but haven't found a build log (or config log). Where can I find that?

Spot-checking the dependencies: 
* I'm not sure if there'll be an issue if both libwlroots-dev and libwlroots-0.18-dev are set?
* separately, it'd be good to have xwayland as a dependency (so it can build support for X11 clients).

**Comment by alexmyczko** [comment]
http://bananas.debian.net/debian/wlmaker/6/wlmaker_0.4-1_arm64.build

i tried with wlroots only then 0.18 added... didnt keep all buildlogs

**Comment by phkaeser** [comment]
Oh, looks like the source package (v0.4.tar.gz) isn't including libbase, ie. the files in `submodules/libbase/...`.

When pulling the data from github directly (https://github.com/phkaeser/wlmaker/blob/main/doc/BUILD.md#get-wayland-maker), there is that extra `git submodule update --init submodules/` step for that.

But yeah, that's not included in github's source package from https://github.com/phkaeser/wlmaker/releases/tag/v0.4. 

* Workaround for now: Please add libbase, eg. by pulling from git.
* Longer-term fix: I'll need to figure out how the source package can include the submodule/ elements.


The actual cmake error:

```
-- Found BISON: /usr/bin/bison (found suitable version "3.8.2", minimum required is "3.0")
CMake Error at CMakeLists.txt:108 (ADD_SUBDIRECTORY):
  The source directory

    /var/www/debian/wlmaker/6/wlmaker-0.4/submodules/libbase

  does not contain a CMakeLists.txt file.
```

**Comment by phkaeser** [comment]
Appears this is a long-known deficiency of github :roll_eyes: -- https://github.com/dear-github/dear-github/issues/214

Workaround is to create an explicit release & build action. Example: https://github.com/pytorch/pytorch/pull/63022/commits/88a06f88da24d9de4fd3cf3a0f18c5327280906f

Will poke at it, but may take a few days until I get to it.

**Comment by phkaeser** [comment]
Got github to create a source archive including the submodules, and created a new release with it:
https://github.com/phkaeser/wlmaker/releases/tag/v0.4.1

The release will have an extra source asset (https://github.com/phkaeser/wlmaker/releases/download/v0.4.1/wlmaker-0.4.1.tar.gz) attached to it; this is a versioned assed.

@alexmyczko => can your tooling make use of that package?
