### ISSUE TITLE
Maybe include a screenshot in the readme?

### ISSUE THREAD

**Issue by 8bitprodigy** [phkaeser/wlmaker#41]
Would show people what it looks like, and would likely draw more people to using/contributing to this project.

**Comment by alexmyczko** [comment]
no screenshot got me so curious to try it myself :)

**Comment by phkaeser** [comment]
Agree, good point.

**Comment by phkaeser** [comment]
I'd be happy for an artist to contribute a more beautiful theme -- for the context of having any idea of the optics, I believe #80 addresses the issue. Closing.
