### ISSUE TITLE
Add support for switching virtual terminal (using CTRL + ALT + Fn)

### ISSUE THREAD

**Issue by markusbkk** [phkaeser/wlmaker#6]
Just curious since I can't find anything in the code.
I noticed that when I launch wlmaker through `/usr/share/wayland-sessions` (in GDM3) I cannot switch between ttys with the usual CTRL + ALT + F-Key

How is this achieved?

**Comment by phkaeser** [comment]
Huh, that's interesting. Also: Unexpected and unintended! Will have to look into it.

FYI, just in case ctrl+window+alt Q should exit wlmaker. So that you're not stuck in that particular tty.

**Comment by markusbkk** [comment]
> Huh, that's interesting. Also: Unexpected and unintended! Will have to look into it.
> 
> FYI, just in case ctrl+window+alt Q should exit wlmaker. So that you're not stuck in that particular tty.

Yea. CTRL + Super + ALT + Q works.

I wonder if the TTY thing is related to the function modifier on my laptop? 
I need to press CTRL + ALT + **FN** + F3 to switch to the next TTY. 

Does your compositor maybe grab them for something else?

**Comment by phkaeser** [comment]
wlmaker doesn't do anything specific on the tty; it just uses libseat and libwlroots keyboard functions. It does (re)set the keymap, though.

I strongly suspect this may have reset the function modifier on your laptop on the particular TTY.

**Have you used other wlroots based compositors, and seen the same issue?** (eg. https://labwc.github.io/ or https://swaywm.org/). That would help me triage the issue.

* if other wlroots-based compositors have the same issue, it's something with wlroots.
* if not, I can walk through the code there and learn how their keyboard initialization differs.

**Comment by markusbkk** [comment]
> wlmaker doesn't do anything specific on the tty; it just uses libseat and libwlroots keyboard functions. It does (re)set the keymap, though.
> 
> I strongly suspect this may have reset the function modifier on your laptop on the particular TTY.
> 
> **Have you used other wlroots based compositors, and seen the same issue?** (eg. https://labwc.github.io/ or https://swaywm.org/). That would help me triage the issue.
> 
>     * if other wlroots-based compositors have the same issue, it's something with wlroots.
> 
>     * if not, I can walk through the code there and learn how their keyboard initialization differs.

I just got a Framework 13 AMD Edition the other day. Will test other wlroots compositors on both my old and new device as well as wlmaker on my new device, as soon as I'm off work and back home. I'll try to provide a comprehensive user report then.

**Comment by Leon-Plickat** [comment]
Friendly pointer from someone who has worked on wlroots based wayland servers before: You have to implement the TTY switching keybinds yourself (or the users could use sysrq, but that's not very ergonomic). The typical `C-A-1` keybind should emit the `XKB_KEY_XF86Switch_VT_1` key symbol (see `xkbcommon-keysyms.h`, same for 2-9). In response you can call `wlr_session_change_vt()`.

**Comment by phkaeser** [comment]
Thanks for the pointer, @Leon-Plickat ! Hadn't been aware of the wlr session module, that's great to learn about!

**Comment by phkaeser** [comment]
Ability to switch to virtual terminals added with #119.

Since the key shortcuts & handling are defined in `etc/wlmaker.plist`, it also can be configured to effectively "lock" the terminal :)

Closing.
