### ISSUE TITLE
Easy scaling for decorations, including icons

### ISSUE THREAD

**Issue by phkaeser** [phkaeser/wlmaker#99]
Reported in #26 by @alexmyczko : "some form of scaling (2x) for the app icons".

Current status:

* wlmaker permits to configure the dimensions & font sizes of decorations.
* wlmaker will currently not scale the icons; but draw them centered into the tiles of dock & clip.

To do:

* Add an example configuration with eg. doubled size, to demonstrate how it can be customized.
* Scale icons used for tiles (dock, clip).
* Verify the optics look sensible.

Note: On the long run, scaling should be configurable via one setting -- and apply & multiple all sizes provided through the style file. The FR here is for just a first attempt to simplify matters.

**Comment by alexmyczko** [comment]
for X11 I found this https://github.com/window-maker/wmaker/issues/44

**Comment by phkaeser** [comment]
Wayland has protocol to configure outputs & scaling options; but I'm afraid wlmaker hasn't evolved to the point of supporting these. I'll want to work on supporting multiple outputs and similar options for v0.5.

Until then: Will have to use the work-around of configuring the decoration size through styles, and using the scaling options for each application (eg. font size for terminal; magnification in browser).
